# Generated by Django 3.2.4 on 2021-08-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_date_posted_post__date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_snippet',
            field=models.TextField(blank=True),
        ),
    ]
